<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="gazebo.urdf.xacro" />
    <xacro:include filename="lidar.urdf.xacro"/>
    <xacro:include filename="depth.urdf.xacro" />
    <xacro:include filename="imu.urdf.xacro" />

    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <xacro:property name="herobrin_body_offset_x" value="${chassis_length/2}"/>
    <xacro:property name="herobrin_body_offset_z" value="${chassis_height+0.19}"/>
    <xacro:property name="herobrin_body_length" value="0.07"/>
    <xacro:property name="herobrin_body_width" value="0.1"/>
    <xacro:property name="herobrin_body_height" value="0.25"/>

    <xacro:property name="herobrin_head_offset_x" value="${chassis_length/2}"/>
    <xacro:property name="herobrin_head_offset_z" value="${chassis_height+0.35}"/>

    <xacro:property name="herobrin_head_length" value="0.12"/>
    <xacro:property name="herobrin_head_width" value="0.12"/>
    <xacro:property name="herobrin_head_height" value="0.12"/>

    <!-- <xacro:property name="herobrin_hand_left_offset_x" value="${chassis_length/2}" />
    <xacro:property name="herobrin_hand_left_offset_y" value="${-herobrin_body_width/2}"/>
    <xacro:property name="herobrin_hand_left_offset_z" value="${0.6+chassis_height}"/>
    <xacro:property name="herobrin_hand_left_length" value="0.15"/>
    <xacro:property name="herobrin_hand_left_width" value="0.3"/>
    <xacro:property name="herobrin_hand_left_height" value="0.1325"/>

    <xacro:property name="herobrin_hand_right_offset_x" value="${chassis_length/2}" />
    <xacro:property name="herobrin_hand_right_offset_y" value="${herobrin_body_width/2}"/>
    <xacro:property name="herobrin_hand_right_offset_z" value="${0.6+chassis_height}"/>
    <xacro:property name="herobrin_hand_right_length" value="0.15"/>
    <xacro:property name="herobrin_hand_right_width" value="0.3"/>
    <xacro:property name="herobrin_hand_right_height" value="0.1325"/> -->

    <xacro:property name="herobrin_leg_left_offset_x" value="${0.22}" />
    <xacro:property name="herobrin_leg_left_offset_y" value="${0}"/>
    <xacro:property name="herobrin_leg_left_offset_z" value="${chassis_height+0.0225}"/>
    <xacro:property name="herobrin_leg_left_length" value="0.05"/>
    <xacro:property name="herobrin_leg_left_width" value="0.1"/>
    <xacro:property name="herobrin_leg_left_height" value="0.1"/>

    <xacro:property name="herobrin_leg_right_offset_x" value="${0.11}" />
    <xacro:property name="herobrin_leg_right_offset_y" value="${0}"/>
    <xacro:property name="herobrin_leg_right_offset_z" value="${chassis_height+0.0225}"/>
    <xacro:property name="herobrin_leg_right_length" value="0.05"/>
    <xacro:property name="herobrin_leg_right_width" value="0.1"/>
    <xacro:property name="herobrin_leg_right_height" value="0.1"/>

    <xacro:property name="mass" value="1.0"/>

    <material name="white">
        <color rgba="0 1 0 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <link name="base_link">
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.138" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name='chassis'>
    
    <inertial>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <mass value="${mass}" />
        <inertia ixx="${(1/12) * mass * (chassis_width*chassis_width+chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * (chassis_length*chassis_length+chassis_height*chassis_height)}" iyz="0.0"
                 izz="${(1/12) * mass * (chassis_length*chassis_length+chassis_width*chassis_width)}" />
    </inertial>
    <visual>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="orange"/>
    </visual>
    <collision>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${caster_wheel_mass}" />
            <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" iyz="0.0"
                     izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- Herobrine Body -->
    <joint name="herobrin_body_joint" type="fixed">
        <parent link="chassis"/>
        <child link="herobrin_body"/>
        <origin xyz="${herobrin_body_offset_x} 0 ${herobrin_body_offset_z}"/>
    </joint>

    <link name="herobrin_body">
        <visual>
            <geometry>
                <box size="${herobrin_body_length} ${herobrin_body_width} ${herobrin_body_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${herobrin_body_length} ${herobrin_body_width} ${herobrin_body_height}"/>
            </geometry>
        </collision>
        <!-- <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.5" />
            <inertia ixx="${(1/12) * 0.5 * (herobrin_body_width*herobrin_body_width + herobrin_body_height*herobrin_body_height)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * 0.5 * (herobrin_body_length*herobrin_body_length + herobrin_body_height*herobrin_body_height)}" iyz="0.0"
                     izz="${(1/12) * 0.5 * (herobrin_body_length*herobrin_body_length + herobrin_body_width*herobrin_body_width)}" />
        </inertial> -->
    </link>

    <gazebo reference="herobrin_body">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- Herobrine Head -->
    <joint name="herobrin_head_joint" type="fixed">
        <parent link="chassis"/>
        <child link="herobrin_head"/>
        <origin xyz="${herobrin_head_offset_x} 0 ${herobrin_head_offset_z}"/>
    </joint>

    <link name="herobrin_head">
        <visual>
            <geometry>
                <box size="${herobrin_head_length} ${herobrin_head_width} ${herobrin_head_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${herobrin_head_length} ${herobrin_head_width} ${herobrin_head_height}"/>
            </geometry>
        </collision>
        <!-- <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.2" />
            <inertia ixx="${(1/12) * 0.2 * (herobrin_head_width*herobrin_head_width + herobrin_head_height*herobrin_head_height)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * 0.2 * (herobrin_head_length*herobrin_head_length + herobrin_head_height*herobrin_head_height)}" iyz="0.0"
                     izz="${(1/12) * 0.2 * (herobrin_head_length*herobrin_head_length + herobrin_head_width*herobrin_head_width)}" />
        </inertial> -->
    </link>

    <gazebo reference="herobrin_head">
        <material>Gazebo/Green</material>
    </gazebo>

 
    <!-- Herobrine Left Leg -->
    <joint name="herobrin_leg_left_joint" type="fixed">
        <parent link="chassis"/>
        <child link="herobrin_leg_left"/>
        <origin xyz="${herobrin_leg_left_offset_x} ${herobrin_leg_left_offset_y} ${herobrin_leg_left_offset_z}"/>
    </joint>

    <link name="herobrin_leg_left">
        <visual>
            <geometry>
                <box size="${herobrin_leg_left_length} ${herobrin_leg_left_width} ${herobrin_leg_left_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${herobrin_leg_left_length} ${herobrin_leg_left_width} ${herobrin_leg_left_height}"/>
            </geometry>
        </collision>
        <!-- <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.1" />
            <inertia ixx="${(1/12) * 0.1 * (herobrin_leg_left_width*herobrin_leg_left_width + herobrin_leg_left_height*herobrin_leg_left_height)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * 0.1 * (herobrin_leg_left_length*herobrin_leg_left_length + herobrin_leg_left_height*herobrin_leg_left_height)}" iyz="0.0"
                     izz="${(1/12) * 0.1 * (herobrin_leg_left_length*herobrin_leg_left_length + herobrin_leg_left_width*herobrin_leg_left_width)}" />
        </inertial> -->
    </link>

    <gazebo reference="herobrin_leg_left">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- Herobrine Right Leg -->
    <joint name="herobrin_leg_right_joint" type="fixed">
        <parent link="chassis"/>
        <child link="herobrin_leg_right"/>
        <origin xyz="${herobrin_leg_right_offset_x} ${herobrin_leg_right_offset_y} ${herobrin_leg_right_offset_z}"/>
    </joint>

    <link name="herobrin_leg_right">
        <visual>
            <geometry>
                <box size="${herobrin_leg_right_length} ${herobrin_leg_right_width} ${herobrin_leg_right_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${herobrin_leg_right_length} ${herobrin_leg_right_width} ${herobrin_leg_right_height}"/>
            </geometry>
        </collision>
        <!-- <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.1" />
            <inertia ixx="${(1/12) * 0.1 * (herobrin_leg_right_width*herobrin_leg_right_width + herobrin_leg_right_height*herobrin_leg_right_height)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * 0.1 * (herobrin_leg_right_length*herobrin_leg_right_length + herobrin_leg_right_height*herobrin_leg_right_height)}" iyz="0.0"
                     izz="${(1/12) * 0.1 * (herobrin_leg_right_length*herobrin_leg_right_length + herobrin_leg_right_width*herobrin_leg_right_width)}" />
        </inertial> -->
    </link>

    <gazebo reference="herobrin_leg_right">
        <material>Gazebo/Green</material>
    </gazebo>

</robot>